export const ADD_STORIES = 'ADD_STORIES';
export const ADD_SAVED = 'ADD_SAVED';
export const DELETE_SAVED = 'DELETE_SAVED';
export const ADD_HISTORY = 'ADD_HISTORY';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';
export const REMOVE_SAVED = 'REMOVE_SAVED';
export const DELETE_HISTORY = 'DELETE_HISTORY';
export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_SORTBY = 'CHANGE_SORTBY';

