export const ROOT_URL = 'http://localhost:8000/products';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const SET_RESULT_COUNT = 'SET_RESULT_COUNT';
export const RESET_QUERY_PARAMS = 'RESET_QUERY_PARAMS';